<?php

/**
 * @file
 * Contains user_sidebar.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_sidebar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_sidebar module.
    case 'help.page.user_sidebar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a sidebar block displaying authenticated user information') . '</p>';
      return $output;

    default:
  }
}
